import '../domain/menu.dart';

const menusData = [
  Menu(
    id: '1',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 01',
    description: 'Lorem ipsum',
    price: 15,
  ),
  Menu(
    id: '2',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 02',
    description: 'Lorem ipsum',
    price: 13,
  ),
  Menu(
    id: '3',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 03',
    description: 'Lorem ipsum',
    price: 17,
  ),
  Menu(
    id: '4',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 04',
    description: 'Lorem ipsum',
    price: 12,
  ),
  Menu(
    id: '5',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 05',
    description: 'Lorem ipsum',
    price: 12,
  ),
  Menu(
    id: '6',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 06',
    description: 'Lorem ipsum',
    price: 12,
  ),
  Menu(
    id: '7',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 07',
    description: 'Lorem ipsum',
    price: 18,
  ),
  Menu(
    id: '8',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 08',
    description: 'Lorem ipsum',
    price: 21,
  ),
  Menu(
    id: '9',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 09',
    description: 'Lorem ipsum',
    price: 11,
  ),
  Menu(
    id: '10',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 10',
    description: 'Lorem ipsum',
    price: 11,
  ),
  Menu(
    id: '11',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 11',
    description: 'Lorem ipsum',
    price: 24,
  ),
  Menu(
    id: '12',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 12',
    description: 'Lorem ipsum',
    price: 22,
  ),
  Menu(
    id: '13',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 13',
    description: 'Lorem ipsum',
    price: 14,
  ),
  Menu(
    id: '14',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 14',
    description: 'Lorem ipsum',
    price: 16,
  ),
  Menu(
    id: '15',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 15',
    description: 'Lorem ipsum',
    price: 16,
  ),
  Menu(
    id: '16',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 16',
    description: 'Lorem ipsum',
    price: 16,
  ),
  Menu(
    id: '17',
    imageUrl: 'assets/menus/menu.jpg',
    title: 'Mon Menu 17',
    description: 'Lorem ipsum',
    price: 16,
  ),
];
