import '../domain/user.dart';

const eatchUsersData = [
  EatchUser(
    id: 'u1',
    userEmail: 'email1@mal.com',
    userNom: 'user1nom',
    userPrenom: 'user1prenom',
    userRole: 'RÔLE_COMPTABLE',
    userUserNom: 'user1nomutilisateur',
  ),
  EatchUser(
    id: 'u2',
    userEmail: 'email2@mal.com',
    userNom: 'user2nom',
    userPrenom: 'user2prenom',
    userRole: 'RÔLE_COMPTABLE',
    userUserNom: 'user2nomutilisateur',
  ),
  EatchUser(
    id: 'u3',
    userEmail: 'email3@mal.com',
    userNom: 'user3nom',
    userPrenom: 'user3prenom',
    userRole: 'RÔLE_COMPTABLE',
    userUserNom: 'user3nomutilisateur',
  ),
  EatchUser(
    id: 'u4',
    userEmail: 'email4@mal.com',
    userNom: 'user4nom',
    userPrenom: 'user4prenom',
    userRole: 'RÔLE_COMPTABLE',
    userUserNom: 'user4nomutilisateur',
  ),
  EatchUser(
    id: 'u5',
    userEmail: 'email5@mal.com',
    userNom: 'user5nom',
    userPrenom: 'user5prenom',
    userRole: 'RÔLE_MANAGER',
    userUserNom: 'user5nomutilisateur',
  ),
  EatchUser(
    id: 'u6',
    userEmail: 'email6@mal.com',
    userNom: 'user6nom',
    userPrenom: 'user6prenom',
    userRole: 'RÔLE_MANAGER',
    userUserNom: 'user6nomutilisateur',
  ),
  EatchUser(
    id: 'u7',
    userEmail: 'email7@mal.com',
    userNom: 'user7nom',
    userPrenom: 'user7prenom',
    userRole: 'RÔLE_MANAGER',
    userUserNom: 'user7nomutilisateur',
  ),
  EatchUser(
    id: 'u8',
    userEmail: 'email8@mal.com',
    userNom: 'user8nom',
    userPrenom: 'user8prenom',
    userRole: 'RÔLE_RH',
    userUserNom: 'user8nomutilisateur',
  ),
  EatchUser(
    id: 'u9',
    userEmail: 'email9@mal.com',
    userNom: 'user9nom',
    userPrenom: 'user9prenom',
    userRole: 'RÔLE_RH',
    userUserNom: 'user9nomutilisateur',
  ),
  EatchUser(
    id: 'u10',
    userEmail: 'email10@mal.com',
    userNom: 'user10nom',
    userPrenom: 'user10prenom',
    userRole: 'RÔLE_RH',
    userUserNom: 'user10nomutilisateur',
  ),
];
